### ISSUE TITLE
Quaxtrip not working with M1 Native

### ISSUE THREAD

**Issue by randallpacker** [damonholzborn/QuaxTrip#4]
Hi Damon... I am retesting Quaxtrip after a long hiatus, and discovered that when Max 8.2 is in M1 Native mode, that Quaxtrip will not initiate a call to the server or client. As soon as I revert to Rosetta it works. Is this a Quaxtrip issue or PD or PDMax? 

Thanks & happy new year!! 

Randall

**Comment by damonholzborn** [comment]
Hi Randal - PDMax has not yet been compiled for M1 native so you’ll have to use Max in Rosetta mode to use Quaxtrip for the time being. I'll leave this issue open until that happens. Happy New Year!

**Comment by fbotello** [comment]
There is a test version of PDMax for M1 now here http://msp.ucsd.edu/Software/pdmax-mac-0.55test1.tgz

**Comment by randallpacker** [comment]
I just happened to update a few days ago to the latest PDMax and Quaxtrip is working fine on an M! MacMini in native.

**Comment by damonholzborn** [comment]
I'm leaving this issue open to remind myself to check for when it's not a "test" version.

**Comment by damonholzborn** [comment]
PdMax for M1 is still a "test" version, but I have successfully tested it (on the recorder branch) so I'm going to go ahead and close this.
