### ISSUE TITLE
Is anyone using Quaxtrip? 

### ISSUE THREAD

**Issue by randallpacker** [damonholzborn/QuaxTrip#5]
Greetings Damon from the Bunker! 

I wanted to return to my work with Quaxtrip for a new project and since I don't see any activity here, I am wondering if Quaxtrip is is still in development and if there are any other users. Since PD and PDMax have been updated since the last time I used Quaxtrip, does that mean it is staying current with any Quacktrip development? I also see that Jacktrip has undergone a transformation with a high degree of marketing & commercialization! Not sure if that is a good thing or not. 

Looking forward to hearing from you. 

Best, Randall

**Comment by damonholzborn** [comment]
Hi Randall,

Quaxtrip is still maintained, though there is not much planned for new features. There will be one feature update soon (a few weeks or so) that includes a synchronized recording feature. Other than that, I don't have anything new planned, though am always open to suggestions. It has been tested with Pd 0.52-2 and PdMax 0.54. I see that PD is now up to 0.53-1, I'll test it with that soon, though I have no reason to expect a problem (famous last words...). Miller has a test version of PdMax for Apple Silicon that I will also try out soon, in the meantime, the Rosetta version is still working fine (and for me, the version I have to use anyway for some of my old VSTs).

I know of a few people who actively use Quaxtrip and I get the occasional support email so there are at least a few of us still using it. 

I haven't been following the latest goings on with Jack Trip. Thanks for bringing that to my attention. Jack Trip Radio sounds interesting.

Damon

**Comment by randallpacker** [comment]
Thanks Damon for the note! I ran Quaxtrip yesterday on an M1 machine (internally in my studio) with all the latest updates and it seemed to be working just fine. 

BTW, I am interested in started in a discussion forum for "artist-broadcasters," and perhaps it might be possible to get you and Miller and Criss Chafe to funnel users of Quax and Quack and Jack to a community forum. There doesn't seem to be a place for discussion other than Github for these platforms, and it would be great to cover a range of topics that are not only development oriented, but also musical/artistic strategies and ideas and concepts. What do you think? Randall

**Comment by damonholzborn** [comment]
That sounds like a great idea. I'd love to hear from others about what they are up to in the space. Keep me posted.
