### ISSUE TITLE
quaxtrip duet audio with video on facetime or zoom

### ISSUE THREAD

**Issue by mygithandle** [damonholzborn/QuaxTrip#7]
a lot of googling, but haven't found whether this can be done, and if so, how.

trying to implement remote practice sessions me-bass, friend-piano with quaxtrip (or quacktrip) so audio is low-latency, but we also have a video connect so we can see each other. don't mind if video quality is crappy, just want to be able to view hands/faces while playing.

Both are on mac, both M1 (i think, will double check)

if possible, grateful if someone can share a brief how-to, or a link to same.  

thanks

**Comment by mygithandle** [comment]
P.S.: we are only a few miles apart in same city and both have pretty high bandwidth internet

also, worst case, we could do two devices at each end, one video/no sound, the other quax/quacktrip

**Comment by damonholzborn** [comment]
I don't know if it's practical (or even possible) to send video across the internet in Max. For this purpose, I've always just used another video service (e.g. FaceTime) alongside, with the sound muted, as you suggest.

**Comment by mygithandle** [comment]
got it, thanks. Actually, vid in a separate process sounds simple enough. I probably should have done some experimentation before posting the question.
