### ISSUE TITLE
Status of Quaxtrip

### ISSUE THREAD

**Issue by randallpacker** [damonholzborn/QuaxTrip#8]
Hi Damon, 

What exactly is the status of Quaxtrip? Are you still working on it? I want to pickup up where I left off a few years ago, and begin integrating the essence of your work into my Telematic Theater project. 

I am particularly interested in a VST or Max for Live version for routing audio in and out of Ableton Live, and perhaps an updated interface to make it super easy for performers who don't tend to be as technically savvy. 

Look forward to hearing from you. 

All the best, Randall

**Comment by damonholzborn** [comment]
I do have one small update that’s just waiting on documentation to release (it adds recording capabilities), but other than that I don’t currently have any other plans for Quaxtrip

I don’t own Live, so I have no plans for a Max4Live device, but I imagine it would pretty simple for someone who wanted to do so. Probably mostly just a matter of refactoring the interface to fit it in the allotted space.

Miller has made a VST version of Quacktrip:
https://msp.ucsd.edu/tools/quacktrip/

I not sure what could be stripped away from the interface to make it easier to use, everything seems pretty necessary. I’m open to suggestions.
